inherit_mode:
  merge:
    - Exclude
    - Include
require:
  - rubocop-performance

AllCops:
  NewCops: enable

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 50
  ExcludedMethods:
    - included
    - class_methods
    - run_callbacks

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'test/**/*_test.rb'

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 14

Style/FrozenStringLiteralComment:
  Enabled: false
